# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-20 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadInterrupto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CausalInterrupcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CausalNoReubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Interruptos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplica_proceso', models.CharField(choices=[(b'S', b'Si'), (b'N', b'No')], max_length=1)),
                ('otras_causas_no_reubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('hastatreintadias_reubicadostemporal_misma_entidad', models.IntegerField(default=0)),
                ('hastatreintadias_reubicadostemporal_mismo_organismo', models.IntegerField(default=0)),
                ('hastatreintadias_reubicadostemporal_otro_organismo', models.IntegerField(default=0)),
                ('hastatreintadias_cobrandogarantiasalarial', models.IntegerField(default=0)),
                ('hastatreintadias_singarantiasalarial', models.IntegerField(default=0)),
                ('hastatreintadias_baja', models.IntegerField(default=0)),
                ('hastatreintadias_propuestoadisponibles', models.IntegerField(default=0)),
                ('entretreintaysesentadias_reubicadostemporal_misma_entidad', models.IntegerField(default=0)),
                ('entretreintaysesentadias_reubicadostemporal_mismo_organismo', models.IntegerField(default=0)),
                ('entretreintaysesentadias_reubicadostemporal_otro_organismo', models.IntegerField(default=0)),
                ('entretreintaysesentadias_cobrandogarantiasalarial', models.IntegerField(default=0)),
                ('entretreintaysesentadias_singarantiasalarial', models.IntegerField(default=0)),
                ('entretreintaysesentadias_baja', models.IntegerField(default=0)),
                ('entretreintaysesentadias_propuestoadisponibles', models.IntegerField(default=0)),
                ('masdesesentayunanno_reubicadostemporal_misma_entidad', models.IntegerField(default=0)),
                ('masdesesentayunanno_reubicadostemporal_mismo_organismo', models.IntegerField(default=0)),
                ('masdesesentayunanno_reubicadostemporal_otro_organismo', models.IntegerField(default=0)),
                ('masdesesentayunanno_cobrandogarantiasalarial', models.IntegerField(default=0)),
                ('masdesesentayunanno_singarantiasalarial', models.IntegerField(default=0)),
                ('masdesesentayunanno_baja', models.IntegerField(default=0)),
                ('masdesesentayunanno_propuestoadisponibles', models.IntegerField(default=0)),
                ('masdeunanno_reubicadostemporal_misma_entidad', models.IntegerField(default=0)),
                ('masdeunanno_reubicadostemporal_mismo_organismo', models.IntegerField(default=0)),
                ('masdeunanno_reubicadostemporal_otro_organismo', models.IntegerField(default=0)),
                ('masdeunanno_cobrandogarantiasalarial', models.IntegerField(default=0)),
                ('masdeunanno_singarantiasalarial', models.IntegerField(default=0)),
                ('masdeunanno_baja', models.IntegerField(default=0)),
                ('masdeunanno_propuestoadisponibles', models.IntegerField(default=0)),
                ('f_hastatreintadias_reubicadostemporal', models.IntegerField(default=0)),
                ('f_hastatreintadias_cobrandogarantiasalarial', models.IntegerField(default=0)),
                ('f_hastatreintadias_singarantiasalarial', models.IntegerField(default=0)),
                ('f_hastatreintadias_baja', models.IntegerField(default=0)),
                ('f_hastatreintadias_propuestoadisponibles', models.IntegerField(default=0)),
                ('f_entretreintaysesentadias_reubicadostemporal', models.IntegerField(default=0)),
                ('f_entretreintaysesentadias_cobrandogarantiasalarial', models.IntegerField(default=0)),
                ('f_entretreintaysesentadias_singarantiasalarial', models.IntegerField(default=0)),
                ('f_entretreintaysesentadias_baja', models.IntegerField(default=0)),
                ('f_entretreintaysesentadias_propuestoadisponibles', models.IntegerField(default=0)),
                ('f_masdesesentayunanno_reubicadostemporal', models.IntegerField(default=0)),
                ('f_masdesesentayunanno_cobrandogarantiasalarial', models.IntegerField(default=0)),
                ('f_masdesesentayunanno_singarantiasalarial', models.IntegerField(default=0)),
                ('f_masdesesentayunanno_baja', models.IntegerField(default=0)),
                ('f_masdesesentayunanno_propuestoadisponibles', models.IntegerField(default=0)),
                ('f_masdeunanno_reubicadostemporal', models.IntegerField(default=0)),
                ('f_masdeunanno_cobrandogarantiasalarial', models.IntegerField(default=0)),
                ('f_masdeunanno_singarantiasalarial', models.IntegerField(default=0)),
                ('f_masdeunanno_baja', models.IntegerField(default=0)),
                ('f_masdeunanno_propuestoadisponibles', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('jovenes_hastatreintadias_reubicadostemporal', models.IntegerField(default=0)),
                ('jovenes_hastatreintadias_cobrandogarantiasalarial', models.IntegerField(default=0)),
                ('jovenes_hastatreintadias_singarantiasalarial', models.IntegerField(default=0)),
                ('jovenes_hastatreintadias_baja', models.IntegerField(default=0)),
                ('jovenes_hastatreintadias_propuestoadisponibles', models.IntegerField(default=0)),
                ('jovenes_entretreintaysesentadias_reubicadostemporal', models.IntegerField(default=0)),
                ('jovenes_entretreintaysesentadias_cobrandogarantiasalarial', models.IntegerField(default=0)),
                ('jovenes_entretreintaysesentadias_singarantiasalarial', models.IntegerField(default=0)),
                ('jovenes_entretreintaysesentadias_baja', models.IntegerField(default=0)),
                ('jovenes_entretreintaysesentadias_propuestoadisponibles', models.IntegerField(default=0)),
                ('jovenes_masdesesentayunanno_reubicadostemporal', models.IntegerField(default=0)),
                ('jovenes_masdesesentayunanno_cobrandogarantiasalarial', models.IntegerField(default=0)),
                ('jovenes_masdesesentayunanno_singarantiasalarial', models.IntegerField(default=0)),
                ('jovenes_masdesesentayunanno_baja', models.IntegerField(default=0)),
                ('jovenes_masdesesentayunanno_propuestoadisponibles', models.IntegerField(default=0)),
                ('jovenes_masdeunanno_reubicadostemporal', models.IntegerField(default=0)),
                ('jovenes_masdeunanno_cobrandogarantiasalarial', models.IntegerField(default=0)),
                ('jovenes_masdeunanno_singarantiasalarial', models.IntegerField(default=0)),
                ('jovenes_masdeunanno_baja', models.IntegerField(default=0)),
                ('jovenes_masdeunanno_propuestoadisponibles', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.ActividadInterrupto')),
                ('causa_interrupcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.CausalInterrupcion')),
                ('causal_no_reubicacion', models.ManyToManyField(to='SGMGU.CausalNoReubicacion')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Entidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Municipio')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Organismo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrganismosAutorizadosRegistrarInterrupto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('tiempo_inicia', models.CharField(max_length=20)),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Organismo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 19, 9, 19, 913000)),
        ),
    ]
