# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-01-09 23:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0002_auto_20191130_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controljovenabandonanns',
            name='causa_no_ubicado',
        ),
        migrations.AddField(
            model_name='controljovenabandonanns',
            name='causa_no_incorporado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.CausalNoIncorporado'),
        ),
        migrations.AlterField(
            model_name='controljovenabandonanns',
            name='incorporado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.EstadoIncorporado'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 18, 57, 37, 345000)),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 18, 57, 37, 327000)),
        ),
        migrations.AlterField(
            model_name='organismosautorizadosregistrarinterrupto',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 18, 57, 37, 486000)),
        ),
        migrations.AlterField(
            model_name='procesodireccionmempleojans',
            name='causa_no_ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.CausalNoUbicado'),
        ),
        migrations.AlterField(
            model_name='procesodireccionmempleojans',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Entidad'),
        ),
        migrations.AlterField(
            model_name='procesodireccionmempleojans',
            name='municipio_entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Municipio'),
        ),
        migrations.AlterField(
            model_name='procesodireccionmempleojans',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Organismo'),
        ),
        migrations.AlterField(
            model_name='procesodireccionmempleojans',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Ubicacion'),
        ),
    ]
