# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-08 20:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0002_auto_20180720_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 16, 40, 54, 296000)),
        ),
        migrations.AlterField(
            model_name='interruptos',
            name='causal_no_reubicacion',
            field=models.ManyToManyField(blank=True, null=True, to='SGMGU.CausalNoReubicacion'),
        ),
    ]
