# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-14 22:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0003_auto_20180808_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 18, 50, 50, 60000)),
        ),
        migrations.RemoveField(
            model_name='interruptos',
            name='causa_interrupcion',
        ),
        migrations.AddField(
            model_name='interruptos',
            name='causa_interrupcion',
            field=models.ManyToManyField(to='SGMGU.CausalInterrupcion'),
        ),
    ]
