# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-01-10 00:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0003_auto_20200109_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='jovenabandonanns',
            name='centro_estudio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Centro_estudio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 19, 23, 19, 417000)),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 19, 23, 19, 402000)),
        ),
        migrations.AlterField(
            model_name='organismosautorizadosregistrarinterrupto',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 19, 23, 19, 527000)),
        ),
    ]
