# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-18 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0004_auto_20180814_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='tipo',
            field=models.CharField(choices=[(b'nm', b'Nivel Medio'), (b'ns', b'Nivel Superior'), (b'oc', b'Obrero Calificado'), (b'eo', b'Escuela de Oficio')], max_length=90),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 12, 36, 0, 573000)),
        ),
        migrations.AlterField(
            model_name='procesoinhabilitacion',
            name='numero_resolucion',
            field=models.CharField(max_length=10, unique_for_year=True),
        ),
    ]
