# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-01-10 00:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0004_auto_20200109_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_usuario',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Centro_estudio'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 19, 28, 32, 803000)),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 19, 28, 32, 788000)),
        ),
        migrations.AlterField(
            model_name='organismosautorizadosregistrarinterrupto',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 19, 28, 32, 897000)),
        ),
    ]
