# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-24 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0005_auto_20181018_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 15, 33, 45, 64000)),
        ),
        migrations.AlterField(
            model_name='interruptos',
            name='causal_no_reubicacion',
            field=models.ManyToManyField(blank=True, to='SGMGU.CausalNoReubicacion'),
        ),
        migrations.AlterField(
            model_name='licenciadossma',
            name='fecha_ubicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
