# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-25 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0006_auto_20190124_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desvinculado',
            name='fecha_ubicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 13, 51, 3, 855000)),
        ),
    ]
