# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-03-14 16:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0007_auto_20200314_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesotrabajadorsocialjans',
            name='causa_desvinculacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.CausalDesvinculacionNS'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 12, 45, 24, 891000)),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 12, 45, 24, 860000)),
        ),
        migrations.AlterField(
            model_name='organismosautorizadosregistrarinterrupto',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 12, 45, 25)),
        ),
    ]
