# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-25 19:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0007_auto_20190125_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='interruptos',
            name='actividad_directos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interruptos',
            name='actividad_indirectos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interruptos',
            name='actividad_todos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interruptos',
            name='causa_interrupcion_accion_lluvia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interruptos',
            name='causa_interrupcion_falta_energia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interruptos',
            name='causa_interrupcion_falta_piezas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interruptos',
            name='causa_interrupcion_orden_paralizacion_temporal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interruptos',
            name='causa_interrupcion_otras_causas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interruptos',
            name='causa_interrupcion_paralizacion_reparacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interruptos',
            name='causa_interrupcion_rotura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interruptos',
            name='informe_valorativo',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/informe_valorativo_interruptos/'),
        ),
        migrations.AddField(
            model_name='interruptos',
            name='total_interruptos_entidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interruptos',
            name='total_trabajadores_entidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 14, 44, 55, 356000)),
        ),
    ]
