# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-25 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0008_auto_20190125_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='interruptos',
            name='actividad_nueva',
            field=models.ManyToManyField(blank=True, related_name='actividad_nueva', to='SGMGU.ActividadInterrupto'),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 14, 54, 8, 491000)),
        ),
    ]
