# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-03-14 16:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0008_auto_20200314_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 12, 45, 55, 344000)),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 12, 45, 55, 329000)),
        ),
        migrations.AlterField(
            model_name='organismosautorizadosregistrarinterrupto',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 12, 45, 55, 454000)),
        ),
        migrations.AlterField(
            model_name='procesotrabajadorsocialjans',
            name='causa_desvinculacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.CausalDesvinculacionNS'),
            preserve_default=False,
        ),
    ]
