# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-30 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0009_auto_20190125_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 16, 17, 1, 949000)),
        ),
        migrations.AlterField(
            model_name='interruptos',
            name='total_interruptos_entidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='interruptos',
            name='total_trabajadores_entidad',
            field=models.IntegerField(),
        ),
    ]
