# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-03-24 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0010_auto_20200314_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterruptosCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trabajadores_entidad', models.IntegerField()),
                ('hospitalizados_covid', models.IntegerField()),
                ('certificado_medico_covid', models.IntegerField()),
                ('permanecen_entidad', models.IntegerField()),
                ('trabajo_distancia', models.IntegerField()),
                ('teletrabajo', models.IntegerField()),
                ('interruptos', models.IntegerField()),
                ('irma_misma_entidad', models.IntegerField()),
                ('irma_otra_entidad_mismo_organismo', models.IntegerField()),
                ('irma_otro_organismo', models.IntegerField()),
                ('ircl_misma_entidad', models.IntegerField()),
                ('ircl_otra_entidad_mismo_organismo', models.IntegerField()),
                ('ircl_otro_organismo', models.IntegerField()),
                ('vinculados_produccion_alimentos', models.IntegerField()),
                ('garantia_salarial_100', models.IntegerField()),
                ('garantia_salarial_60', models.IntegerField()),
                ('locales_cerrados', models.IntegerField()),
                ('total_locales', models.IntegerField()),
                ('causa_interrupcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.CausalInterrupcion')),
            ],
        ),
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 0, 7, 31, 742000)),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 0, 7, 31, 663000)),
        ),
        migrations.AlterField(
            model_name='organismosautorizadosregistrarinterrupto',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 0, 7, 31, 887000)),
        ),
        migrations.AddField(
            model_name='interruptoscovid',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Entidad'),
        ),
        migrations.AddField(
            model_name='interruptoscovid',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Municipio'),
        ),
        migrations.AddField(
            model_name='interruptoscovid',
            name='organismo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Organismo'),
        ),
    ]
