# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-04 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0010_auto_20190130_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interruptos',
            name='actividad',
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 13, 7, 11, 692000)),
        ),
    ]
