# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-03-24 04:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0011_auto_20200324_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='interruptoscovid',
            name='fecha_modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interruptoscovid',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 0, 31, 12, 18000)),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 0, 31, 12, 2000)),
        ),
        migrations.AlterField(
            model_name='organismosautorizadosregistrarinterrupto',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 0, 31, 12, 136000)),
        ),
    ]
