# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-04 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0011_auto_20190204_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 13, 42, 47, 523000)),
        ),
        migrations.AlterField(
            model_name='interruptos',
            name='informe_valorativo',
            field=models.FileField(default=None, upload_to=b'uploads/informe_valorativo_interruptos/'),
            preserve_default=False,
        ),
    ]
