# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-03-24 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0012_auto_20200324_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 9, 19, 32, 188000)),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 9, 19, 31, 927000)),
        ),
        migrations.AlterField(
            model_name='interruptoscovid',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Municipio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organismosautorizadosregistrarinterrupto',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 9, 19, 35, 510000)),
        ),
    ]
