# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-05 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0014_auto_20190205_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
