# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-05 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0015_auto_20190205_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 5, 27, 777000, tzinfo=utc)),
        ),
    ]
