# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-06 20:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0017_auto_20190206_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobacionanualempleoestatal',
            name='fuente_procedencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.FuenteProcedencia'),
            preserve_default=False,
        ),
    ]
