# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-06 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0019_auto_20190226_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interruptos',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
