# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-15 18:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0024_auto_20190315_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadinterrupto',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 484000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='asociacion',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 465000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='causalbaja',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 384000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='causalinterrupcion',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 485000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='causalnoaceptacion',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 382000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='causalnoincorporado',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 381000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='causalnoreubicacion',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 486000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='causalnoubicado',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 385000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='controllicenciadossma',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 397000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='delito',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 402000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='desvinculado',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 421000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discapacidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 467000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discapacitados',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 473000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='egresadosefi',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 462000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='egresadosescuelasconducta',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 455000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='egresadosescuelasespeciales',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 447000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='egresadosestablecimientospenitenciarios',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 410000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 374000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='estadoincorporado',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 387000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 14, 57, 59, 356000)),
        ),
        migrations.AlterField(
            model_name='fuenteprocedencia',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 399000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='licenciadossma',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 393000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='menores',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 439000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='motivoegreso',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 403000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nivelescolar',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 380000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organismosautorizadosregistrarinterrupto',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 14, 57, 59, 487000)),
        ),
        migrations.AlterField(
            model_name='personasriesgo',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 480000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tmedioocalificadoeoficio',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 428000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 18, 57, 59, 386000, tzinfo=utc)),
        ),
    ]
