# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-21 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0025_auto_20190315_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadinterrupto',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 8, 50000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='asociacion',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 8, 32000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='causalbaja',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 954000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='causalinterrupcion',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 8, 52000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='causalnoaceptacion',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 953000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='causalnoincorporado',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 952000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='causalnoreubicacion',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 8, 53000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='causalnoubicado',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 956000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='controllicenciadossma',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 968000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='delito',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 973000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='desvinculado',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 990000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discapacidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 8, 34000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discapacitados',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 8, 39000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='egresadosefi',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 8, 29000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='egresadosescuelasconducta',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 8, 21000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='egresadosescuelasespeciales',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 8, 14000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='egresadosestablecimientospenitenciarios',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 980000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 945000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='estadoincorporado',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 958000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 13, 35, 7, 928000)),
        ),
        migrations.AlterField(
            model_name='fuenteprocedencia',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 970000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='interruptos',
            name='actividad_todos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='licenciadossma',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 964000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='menores',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 8, 6000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='motivoegreso',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 974000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nivelescolar',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 950000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organismosautorizadosregistrarinterrupto',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 13, 35, 8, 55000)),
        ),
        migrations.AlterField(
            model_name='personasriesgo',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 8, 47000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tmedioocalificadoeoficio',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 998000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 17, 35, 7, 957000, tzinfo=utc)),
        ),
    ]
