# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-28 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0031_auto_20190328_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 15, 3, 47, 866000)),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 15, 3, 47, 859000)),
        ),
        migrations.AlterField(
            model_name='licenciadossma',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='organismosautorizadosregistrarinterrupto',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 15, 3, 47, 976000)),
        ),
    ]
